"""initial schema

Revision ID: 3cde1e76c19c
Revises: 
Create Date: 2026-03-19 11:28:10.742515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3cde1e76c19c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('quote_requests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('specs', sa.Text(), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('radius_miles', sa.Integer(), nullable=False),
    sa.Column('dealer_locator_url', sa.String(length=2048), nullable=True),
    sa.Column('reference_code', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('pending', 'searching', 'enriching', 'sending', 'monitoring', 'completed', name='quoterequeststatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_requests_reference_code'), 'quote_requests', ['reference_code'], unique=True)
    op.create_index(op.f('ix_quote_requests_user_id'), 'quote_requests', ['user_id'], unique=False)
    op.create_table('dealers',
    sa.Column('quote_request_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['quote_request_id'], ['quote_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealers_quote_request_id'), 'dealers', ['quote_request_id'], unique=False)
    op.create_table('pipeline_jobs',
    sa.Column('quote_request_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='pipelinejobstatus'), nullable=False),
    sa.Column('progress', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['quote_request_id'], ['quote_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_jobs_quote_request_id'), 'pipeline_jobs', ['quote_request_id'], unique=False)
    op.create_table('outreach_records',
    sa.Column('dealer_id', sa.UUID(), nullable=False),
    sa.Column('quote_request_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.Enum('email', 'contact_form', name='outreachmethod'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', 'replied', name='outreachstatus'), nullable=False),
    sa.Column('email_subject', sa.String(length=500), nullable=True),
    sa.Column('email_body', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_request_id'], ['quote_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_records_dealer_id'), 'outreach_records', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_outreach_records_quote_request_id'), 'outreach_records', ['quote_request_id'], unique=False)
    op.create_table('replies',
    sa.Column('outreach_record_id', sa.UUID(), nullable=False),
    sa.Column('quote_request_id', sa.UUID(), nullable=False),
    sa.Column('dealer_id', sa.UUID(), nullable=False),
    sa.Column('raw_body', sa.Text(), nullable=False),
    sa.Column('parsed_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('parsed_lead_time', sa.String(length=255), nullable=True),
    sa.Column('parsed_availability', sa.String(length=255), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outreach_record_id'], ['outreach_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_request_id'], ['quote_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replies_dealer_id'), 'replies', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_replies_outreach_record_id'), 'replies', ['outreach_record_id'], unique=False)
    op.create_index(op.f('ix_replies_quote_request_id'), 'replies', ['quote_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_replies_quote_request_id'), table_name='replies')
    op.drop_index(op.f('ix_replies_outreach_record_id'), table_name='replies')
    op.drop_index(op.f('ix_replies_dealer_id'), table_name='replies')
    op.drop_table('replies')
    op.drop_index(op.f('ix_outreach_records_quote_request_id'), table_name='outreach_records')
    op.drop_index(op.f('ix_outreach_records_dealer_id'), table_name='outreach_records')
    op.drop_table('outreach_records')
    op.drop_index(op.f('ix_pipeline_jobs_quote_request_id'), table_name='pipeline_jobs')
    op.drop_table('pipeline_jobs')
    op.drop_index(op.f('ix_dealers_quote_request_id'), table_name='dealers')
    op.drop_table('dealers')
    op.drop_index(op.f('ix_quote_requests_user_id'), table_name='quote_requests')
    op.drop_index(op.f('ix_quote_requests_reference_code'), table_name='quote_requests')
    op.drop_table('quote_requests')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
